spring:
  application:
    name: AIChat

llm:
  provider: gemini
  gemini:
    model: gemini-2.5-flash-lite
    api:
      key: abcd*****74123
  openai:
    model: abcd-1.0
    api:
      key: abcdefgh0-asfas4fasf

marv1n:
  doc:
    path: classpath:docs/company-handbook.txt