spring:
  application:
    name: AIChat
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

llm:
  provider: gemini
  gemini:
    model: gemini-2.5-flash-lite
    api:
      key: abcd*****74123
  openai:
    model: abcd-1.0
    api:
      key: abcdefgh0-asfas4fasf

marv1n:
  doc:
    file:
      path: classpath:docs/
    s3:
      path: test_bucket